### ISSUE TITLE
jajub unnecessary slow due to 10 ms polling

### ISSUE THREAD

**Issue by subes** [org-arl/jajub#2]
Hi,

thanks a lot for this great library. I made some modifications in a fork here: https://github.com/invesdwin/invesdwin-context-julia/blob/master/invesdwin-context-julia-parent/invesdwin-context-julia-runtime-jajub/src/main/java/de/invesdwin/context/julia/runtime/jajub/pool/ModifiedJuliaBridge.java

Most notably the 10 ms poll makes things very slow. By replacing it with a spinning waiter I got my testcase execution down from 32 seconds to 11 seconds. This matches the speed of https://github.com/jbytecode/juliacaller.

- Also currently JuliaBridge does not support Char datatype.
- I also removed the `__ans__ `getting after each call
- I also made the get call a bit more robust and faster for String/Char responses
- had to replace java util logging with Slf4j to actually see logs
  - removed the TERMINATOR outputs from the logs to allow easier debugging of scripts
- support multi-line commands by wrapping into "begin ... end"
- removed the versioninfo() call during startup because it is quite slow
- print stderr output as red and detect execution errors with that
- fix utf8 encoding

If you like you can extract some of these improvements from the fork.

**Comment by mchitre** [comment]
Thanks for the great work. I'll be happy to take in PRs to review and incorporate the changes.

P.S. Most of the changes seem reasonable, but I'm not sure I understand why you needed Slf4j instead of Java logging.

**Comment by subes** [comment]
I don't understand either. I guess jul-to-slf4j does not really work. I won't create a PR, it is better you pick the changes that you like by diffing both files. The modified implementation uses some classes from invesdwin. So integrating those changes here will not be a 1-1 match.

**Comment by mchitre** [comment]
This repo is no longer being maintained and is now archived. So this issue won't be fixed.
